# Site settings
title: Naveen's Blog
header-img: img/home-bg.jpg
email: 
description: "Naveen's personal blog"
baseurl: "/cleanjekyll"
url: 
twitter_username: 
github_username:  
facebook_username:  

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
